version: '3.8'

services:
  sfs-server:
    build:
      context: ./sfs_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sfs_server:/sfs_server
      - ./sfs_server/media:/usr/src/app/media
      - ./sfs_server/static:/usr/src/app/static
    command: daphne --bind 0.0.0.0 --port 8000 configuration.asgi:application
    environment:
      - DB_HOST=sfs-database
      - DB_NAME=sfs_api_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DEBUG=1
      - ALLOWED_HOSTS=*
    depends_on:
      - sfs-database

  sfs-client:
    build:
      context: ./sfs_client/client
      dockerfile: Dockerfile
    command: ng serve --host 0.0.0.0
    container_name: sfs-client
    depends_on:
      - sfs-server
    environment:
      - CHROME_BIN=chromium-browser
    ports:
      - 4200:4200

  sfs-database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=sfs_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - sfs-database:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: sfs-nginx
    depends_on:
      - sfs-server
      - sfs-client
    ports:
      - 8080:80
    restart: always
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static


volumes:
  sfs-database:
  media:
  static:
