version: '3.8'

services:
  sfs-server:
    build:
      context: ./sfs_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sfs-server:/sfs-server
    command: >
      sh -c "python manage.py wait_for_online_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=sfs-database
      - DB_NAME=sfs_api_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DEBUG=1
      - ALLOWED_HOSTS=0.0.0.0
    depends_on:
      - sfs-database

  sfs-client:
    build:
      context: ./sfs_client/client
      dockerfile: Dockerfile
    command: ng serve --host 0.0.0.0
    container_name: sfs-client
    depends_on:
      - sfs-server
    environment:
      - CHROME_BIN=chromium-browser
    ports:
      - 4200:4200
    volumes:
      - ./sfs-client/client:/usr/src/app

  sfs-database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=sfs_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 20s
      interval: 5s
      retries: 3
