# Generated by Django 3.1.3 on 2020-11-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_size',
        ),
    ]
